export const LOADING_MERCHANT_LIST = 'LOADING_MERCHANT_LIST';
export const RECEIVE_MERCHANTS_LIST = 'RECEIVE_MERCHANTS_LIST';
export const LOADING_MERCHANT_ITEM = 'LOADING_MERCHANT_ITEM';
export const RECEIVE_MERCHANTS_ITEM = 'RECEIVE_MERCHANTS_ITEM';
export const DELETE_MERCHANT_ITEM = 'DELETE_MERCHANT_ITEM';
