export const LOADING_MERCHANT_LIST = 'LOADING_MERCHANT_LIST';
export const RECEIVE_MERCHANTS_LIST = 'RECEIVE_MERCHANTS_LIST';
export const LOADING_MERCHANT_ITEM = 'LOADING_MERCHANT_ITEM';
export const RECEIVE_MERCHANTS_ITEM = 'RECEIVE_MERCHANTS_ITEM';
export const DELETE_MERCHANT_ITEM = 'DELETE_MERCHANT_ITEM';
export const SORT_LIST_BY_NAME = 'SORT_LIST_BY_NAME';
export const SORT_LIST_BY_AMOUNT = 'SORT_LIST_BY_AMOUNT';
export const SORT_LIST_BY_DATE = 'SORT_LIST_BY_DATE';
